name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 当 main 分支更新时触发部署

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm run build  # 如果有构建步骤，请在这里指定

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
          artifact_name: github-pages
          preview: false
